import {
  decodeText,
  inspectVocabularyCsv,
  parseCsv,
  vocabularyCsvToCards,
} from './CsvImportService';

describe('CsvImportService', () => {
  test('parses quoted commas, quotes, and multiline fields', () => {
    const rows = parseCsv('word,translation,context\nход,"move, turn","He said ""check""\nthen moved"');

    expect(rows).toEqual([
      ['word', 'translation', 'context'],
      ['ход', 'move, turn', 'He said "check"\nthen moved'],
    ]);
  });

  test('converts vocabulary CSV rows into markdown cards', () => {
    const cards = vocabularyCsvToCards(
      [
        'word,translation,context,context_translated,occurrences,forms',
        'слон,bishop,"Белый слон берет коня.","The white bishop takes the knight.",135,"слон; слона"',
      ].join('\n')
    );

    expect(cards).toHaveLength(1);
    expect(cards[0].front).toBe('слон');
    expect(cards[0].back).toContain('bishop');
    expect(cards[0].back).toContain('**Context**');
    expect(cards[0].back).toContain('> Белый слон берет коня.');
    expect(cards[0].back).toContain('**Context translation**');
    expect(cards[0].back).toContain('> The white bishop takes the knight.');
    expect(cards[0].back).toContain('Occurrences: 135');
    expect(cards[0].back).toContain('Forms: слон; слона');
  });

  test('detects Excel-style semicolon CSV and language-suffixed translations', () => {
    const result = inspectVocabularyCsv(
      [
        'sep=;',
        'lemma;translation_ru;source_sentence;translated_sentence;frequency;word_forms',
        'compiler;компилятор;The compiler emitted a warning.;Компилятор выдал предупреждение.;3;compilers',
      ].join('\r\n')
    );

    expect(result.delimiter).toBe(';');
    expect(result.headerRowNumber).toBe(2);
    expect(result.cards).toHaveLength(1);
    expect(result.cards[0].front).toBe('compiler');
    expect(result.cards[0].back).toContain('компилятор');
    expect(result.cards[0].back).toContain('> The compiler emitted a warning.');
    expect(result.cards[0].back).toContain('> Компилятор выдал предупреждение.');
    expect(result.cards[0].back).toContain('Occurrences: 3');
    expect(result.cards[0].back).toContain('Forms: compilers');
  });

  test('finds a tab-delimited header after a generator preamble', () => {
    const result = inspectVocabularyCsv(
      [
        'Generated by LangPrep',
        'headword\tmeaning\texample_translation',
        'robust\tнадежный\tЭто надежное решение.',
      ].join('\n')
    );

    expect(result.delimiter).toBe('tab');
    expect(result.headerRowNumber).toBe(2);
    expect(result.cards[0].front).toBe('robust');
    expect(result.cards[0].back).toContain('Это надежное решение.');
  });

  test('reports rows skipped because a required value is empty', () => {
    const result = inspectVocabularyCsv(
      ['word,translation', 'valid,действительный', 'missing translation,', ',missing word'].join(
        '\n'
      )
    );

    expect(result.cards).toHaveLength(1);
    expect(result.skippedRows).toBe(2);
  });

  test('treats quotes inside unquoted values as literal characters', () => {
    const cards = vocabularyCsvToCards('word,translation\ndisplay,6" screen');

    expect(cards[0].back).toBe('6" screen');
  });

  test('decodes UTF-16 little-endian files with a byte-order mark', () => {
    const text = 'word,translation\ncache,кэш';
    const bytes = new Uint8Array(2 + text.length * 2);
    bytes.set([0xff, 0xfe]);
    for (let index = 0; index < text.length; index += 1) {
      const codePoint = text.charCodeAt(index);
      bytes[2 + index * 2] = codePoint & 0xff;
      bytes[3 + index * 2] = codePoint >> 8;
    }

    expect(decodeText(bytes.buffer)).toBe(text);
    expect(vocabularyCsvToCards(decodeText(bytes.buffer))[0].front).toBe('cache');
  });

  test('requires word and translation columns', () => {
    expect(() => vocabularyCsvToCards('front_only\nслон')).toThrow(
      'CSV must include word and translation columns.'
    );
  });
});
